name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full depth)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'repo'  # Critical fix - isolates in subdirectory

      - name: Verify files
        working-directory: ./repo
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          [ -f package.json ] || exit 1

      - name: Install dependencies
        working-directory: ./repo
        run: |
          npm install
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Build project
        working-directory: ./repo
        run: npm run build

      - name: Deploy to Vercel
        working-directory: ./repo
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
