name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code with FULL history/depth
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are fetched

      # Step 2: Debug (optional - verify files)
      - name: List files
        run: ls -la

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm cache verify  # Clears npm cache issues

      # Step 4: Build
      - name: Build project
        run: npm run build

      # Step 5: Deploy to Vercel
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
